import React, { useEffect, useRef, useState } from 'react';
import DigitalWaterDemoChrome from './DigitalWaterDemoChrome';
import DigitalWaterWaterCanvas from './DigitalWaterWaterCanvas';
import { FILTER_TYPES, TOTAL_WATER, TYPE_SHOWCASE } from './digitalWaterDemoData';
import './DigitalWaterDemoShared.css';

const AUDIO_BARS = [18, 34, 52, 28, 64, 42, 72, 36, 58, 24, 48, 66, 30, 54, 40, 62];

const STEPS = [
  { target: 'filter-text', activeType: 'Text', simulationRunning: false, audioPlaying: false, duration: 1200 },
  { target: 'idle', activeType: 'Text', simulationRunning: false, audioPlaying: false, duration: 2200 },
  { target: 'filter-simulation', activeType: 'Simulation', simulationRunning: false, audioPlaying: false, duration: 1300 },
  { target: 'idle', activeType: 'Simulation', simulationRunning: true, audioPlaying: false, duration: 2400 },
  { target: 'filter-audio', activeType: 'Audio', simulationRunning: false, audioPlaying: false, duration: 1300 },
  { target: 'play-audio', activeType: 'Audio', simulationRunning: false, audioPlaying: false, duration: 1100 },
  { target: 'play-audio', activeType: 'Audio', simulationRunning: false, audioPlaying: true, duration: 2200 },
  { target: 'idle', activeType: 'Audio', simulationRunning: false, audioPlaying: true, duration: 1000 },
];

const TextArtifactView = ({ artifact }) => (
  <div className="dwd-types__text-view">
    <p className="dwd-types__text-body">{artifact.preview}</p>
    {artifact.author ? (
      <p className="dwd-types__text-author">{artifact.author}</p>
    ) : null}
  </div>
);

const AudioArtifactView = ({ playing }) => (
  <div className="dwd-types__audio-view">
    <p className="dwd-types__audio-label">Procedural Water Audio</p>
    <div className={`dwd-types__waveform ${playing ? 'is-playing' : ''}`}>
      {AUDIO_BARS.map((height, index) => (
        <span
          key={index}
          className="dwd-types__wave-bar"
          style={{ '--bar-height': `${height}%`, '--bar-delay': `${index * 0.05}s` }}
        />
      ))}
    </div>
    <p className="dwd-types__audio-status">
      {playing ? 'Generating water sounds...' : 'Press play to hear artifact'}
    </p>
  </div>
);

const ArtifactMeta = ({ artifact }) => (
  <div className="dwd-types__meta">
    <h3 className="dwd-types__title">LIQUID ARTIFACT #{artifact.id}</h3>
    <div className="dwd-types__meta-grid">
      <div><span>TYPE:</span> <span>{artifact.type.toUpperCase()}</span></div>
      <div><span>WATER REQUIRED:</span> <span>{artifact.water}L</span></div>
      <div><span>GENERATED BY:</span> <span>{artifact.generator}</span></div>
      <div><span>CREATED:</span> <span>{artifact.created}</span></div>
    </div>
  </div>
);

const DigitalWaterTypesDemo = ({ className = '', style }) => {
  const containerRef = useRef(null);
  const targetRefs = useRef({});
  const [stepIndex, setStepIndex] = useState(0);
  const [cursor, setCursor] = useState({ x: 48, y: 48, visible: false });
  const [running, setRunning] = useState(false);

  const step = STEPS[stepIndex];
  const isIdle = step.target === 'idle';
  const typeKey = step.activeType.toLowerCase();
  const artifact = TYPE_SHOWCASE[typeKey];

  const setTargetRef = (key) => (node) => {
    if (node) targetRefs.current[key] = node;
    else delete targetRefs.current[key];
  };

  useEffect(() => {
    const node = containerRef.current;
    if (!node) return undefined;

    const observer = new IntersectionObserver(
      ([entry]) => setRunning(entry.isIntersecting),
      { threshold: 0.35 }
    );
    observer.observe(node);
    return () => observer.disconnect();
  }, []);

  useEffect(() => {
    if (!running) return undefined;

    const updateCursor = () => {
      const container = containerRef.current;
      if (!container || isIdle) {
        setCursor((prev) => ({ ...prev, visible: false }));
        return;
      }

      const target = targetRefs.current[step.target];
      if (!target) {
        setCursor((prev) => ({ ...prev, visible: false }));
        return;
      }

      const containerRect = container.getBoundingClientRect();
      const targetRect = target.getBoundingClientRect();
      setCursor({
        x: targetRect.left - containerRect.left + targetRect.width * 0.55,
        y: targetRect.top - containerRect.top + targetRect.height * 0.5,
        visible: true,
      });
    };

    updateCursor();
    window.addEventListener('resize', updateCursor);
    return () => window.removeEventListener('resize', updateCursor);
  }, [step, running, isIdle]);

  useEffect(() => {
    if (!running) return undefined;

    const timer = window.setTimeout(() => {
      setStepIndex((current) => (current + 1) % STEPS.length);
    }, step.duration);

    return () => window.clearTimeout(timer);
  }, [stepIndex, running, step.duration]);

  const renderStage = () => {
    if (typeKey === 'text') {
      return <TextArtifactView artifact={artifact} />;
    }

    if (typeKey === 'simulation') {
      return (
        <div className="dwd-types__simulation-view">
          <DigitalWaterWaterCanvas
            running={step.simulationRunning}
            className="dwd-types__simulation-canvas"
          />
          {step.simulationRunning ? (
            <div className="dwd-types__simulation-badge">Simulation Running</div>
          ) : null}
        </div>
      );
    }

    return <AudioArtifactView playing={step.audioPlaying} />;
  };

  return (
    <DigitalWaterDemoChrome
      containerRef={containerRef}
      cursor={cursor}
      artifactCount={6}
      totalWater={TOTAL_WATER}
      className={className}
      style={style}
    >
      <div className="dwd-types">
        <div className="dwd-types__toolbar">
          <div className="dwd-archive__filters">
            {FILTER_TYPES.map((filter) => {
              const key = `filter-${filter.toLowerCase()}`;
              return (
                <span
                  key={filter}
                  ref={setTargetRef(key)}
                  className={[
                    'dwd-archive__filter',
                    step.activeType === filter ? 'is-active' : '',
                    step.target === key ? 'is-hovered' : '',
                  ].filter(Boolean).join(' ')}
                >
                  {filter}
                </span>
              );
            })}
          </div>
        </div>

        <div className="dwd-types__layout">
          <div className="dwd-types__stage" key={typeKey}>
            {renderStage()}
          </div>

          <aside className="dwd-types__sidebar">
            <ArtifactMeta artifact={artifact} />

            {typeKey === 'audio' ? (
              <span
                ref={setTargetRef('play-audio')}
                className={[
                  'dwd-simulation__button',
                  step.audioPlaying ? 'is-active' : '',
                  step.target === 'play-audio' ? 'is-hovered' : '',
                ].filter(Boolean).join(' ')}
              >
                {step.audioPlaying ? 'Water Audio: ON' : 'Enable Water Audio'}
              </span>
            ) : null}

            {typeKey === 'simulation' ? (
              <div className="dwd-simulation__params">
                <div>Grid: 28</div>
                <div>Dampening: 0.42</div>
                <div>Tension: 0.68</div>
              </div>
            ) : null}

            {typeKey === 'text' ? (
              <p className="dwd-types__note">
                Generated text is rendered as a liquid artifact — each line carries a measured water footprint.
              </p>
            ) : null}
          </aside>
        </div>
      </div>
    </DigitalWaterDemoChrome>
  );
};

export default DigitalWaterTypesDemo;
