import React, { useEffect, useRef, useState } from 'react';
import DigitalWaterDemoChrome from './DigitalWaterDemoChrome';
import DigitalWaterWaterCanvas from './DigitalWaterWaterCanvas';
import { DEMO_ARTIFACTS, TOTAL_WATER } from './digitalWaterDemoData';
import './DigitalWaterDemoShared.css';

const ARTIFACT = DEMO_ARTIFACTS[0];

const STEPS = [
  { target: 'start', running: false, duration: 1200 },
  { target: 'start', running: true, duration: 2200 },
  { target: 'audio', running: true, duration: 1400 },
  { target: 'audio', running: true, audioOn: true, duration: 1800 },
  { target: 'idle', running: true, audioOn: true, duration: 1200 },
  { target: 'stop', running: true, audioOn: true, duration: 1300 },
  { target: 'stop', running: false, audioOn: true, duration: 1600 },
  { target: 'idle', running: false, audioOn: true, duration: 1000 },
];

const DigitalWaterSimulationDemo = ({ className = '', style }) => {
  const containerRef = useRef(null);
  const targetRefs = useRef({});
  const [stepIndex, setStepIndex] = useState(0);
  const [cursor, setCursor] = useState({ x: 48, y: 48, visible: false });
  const [running, setRunning] = useState(false);

  const step = STEPS[stepIndex];
  const isIdle = step.target === 'idle';
  const simulationRunning = step.running;
  const audioOn = step.audioOn;

  const setTargetRef = (key) => (node) => {
    if (node) targetRefs.current[key] = node;
    else delete targetRefs.current[key];
  };

  useEffect(() => {
    const node = containerRef.current;
    if (!node) return undefined;

    const observer = new IntersectionObserver(
      ([entry]) => setRunning(entry.isIntersecting),
      { threshold: 0.35 }
    );
    observer.observe(node);
    return () => observer.disconnect();
  }, []);

  useEffect(() => {
    if (!running) return undefined;

    const updateCursor = () => {
      const container = containerRef.current;
      if (!container || isIdle) {
        setCursor((prev) => ({ ...prev, visible: false }));
        return;
      }

      const target = targetRefs.current[step.target];
      if (!target) {
        setCursor((prev) => ({ ...prev, visible: false }));
        return;
      }

      const containerRect = container.getBoundingClientRect();
      const targetRect = target.getBoundingClientRect();
      setCursor({
        x: targetRect.left - containerRect.left + targetRect.width * 0.55,
        y: targetRect.top - containerRect.top + targetRect.height * 0.5,
        visible: true,
      });
    };

    updateCursor();
    window.addEventListener('resize', updateCursor);
    return () => window.removeEventListener('resize', updateCursor);
  }, [step, running, isIdle]);

  useEffect(() => {
    if (!running) return undefined;

    const timer = window.setTimeout(() => {
      setStepIndex((current) => (current + 1) % STEPS.length);
    }, step.duration);

    return () => window.clearTimeout(timer);
  }, [stepIndex, running, step.duration]);

  return (
    <DigitalWaterDemoChrome
      containerRef={containerRef}
      cursor={cursor}
      artifactCount={DEMO_ARTIFACTS.length}
      totalWater={TOTAL_WATER}
      className={className}
      style={style}
    >
      <div className="dwd-simulation">
        <div className="dwd-simulation__stage">
          <div className="dwd-simulation__canvas-wrap">
            <DigitalWaterWaterCanvas running={simulationRunning} className="dwd-simulation__canvas" />
            {!simulationRunning ? (
              <div className="dwd-simulation__overlay">
                <p className="dwd-simulation__overlay-text">{ARTIFACT.preview}</p>
              </div>
            ) : null}
          </div>
        </div>

        <aside className="dwd-simulation__sidebar">
          <h3 className="dwd-simulation__title">LIQUID ARTIFACT #{ARTIFACT.id}</h3>

          <div className="dwd-simulation__meta">
            <div className="dwd-simulation__meta-row">
              <span>TYPE:</span> <span>{ARTIFACT.type.toUpperCase()}</span>
            </div>
            <div className="dwd-simulation__meta-row">
              <span>WATER REQUIRED:</span> <span>{ARTIFACT.water}L</span>
            </div>
            <div className="dwd-simulation__meta-row">
              <span>GENERATED BY:</span> <span>{ARTIFACT.generator}</span>
            </div>
            <div className="dwd-simulation__meta-row">
              <span>CREATED:</span> <span>{ARTIFACT.created}</span>
            </div>
          </div>

          <div className="dwd-simulation__controls">
            <div className="dwd-simulation__status">
              Water Simulation: {simulationRunning ? 'Running' : 'Stopped'}
              <br />
              Water Audio: {audioOn ? 'ON' : 'OFF'}
            </div>

            <span
              ref={setTargetRef('start')}
              className={[
                'dwd-simulation__button',
                simulationRunning ? 'is-active' : '',
                step.target === 'start' ? 'is-hovered' : '',
              ].filter(Boolean).join(' ')}
            >
              {simulationRunning ? 'Simulation Running' : 'Start Simulation'}
            </span>

            <span
              ref={setTargetRef('stop')}
              className={[
                'dwd-simulation__button',
                !simulationRunning ? 'is-active' : '',
                step.target === 'stop' ? 'is-hovered' : '',
              ].filter(Boolean).join(' ')}
            >
              Stop Simulation
            </span>

            <span
              ref={setTargetRef('audio')}
              className={[
                'dwd-simulation__button',
                audioOn ? 'is-active' : '',
                step.target === 'audio' ? 'is-hovered' : '',
              ].filter(Boolean).join(' ')}
            >
              {audioOn ? 'Disable Water Audio' : 'Enable Water Audio'}
            </span>

            {simulationRunning ? (
              <div className="dwd-simulation__params">
                <div>Grid: 28</div>
                <div>Dampening: 0.42</div>
                <div>Tension: 0.68</div>
              </div>
            ) : null}
          </div>
        </aside>
      </div>
    </DigitalWaterDemoChrome>
  );
};

export default DigitalWaterSimulationDemo;
